package com.lei.entity;
// Generated 2017-9-20 15:20:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TClassify generated by hbm2java
 */
public class TClassify implements java.io.Serializable {

	private String id;
	private String text;
	private Date createTime;
	private Date updateTime;

	public TClassify() {
	}

	public TClassify(String id) {
		this.id = id;
	}

	public TClassify(String id, String text, Date createTime, Date updateTime) {
		this.id = id;
		this.text = text;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
