package com.lei.entity;
// Generated 2017-9-20 20:25:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TFilm generated by hbm2java
 */
public class TFilm implements java.io.Serializable {

	private String id;
	private String name;
	private String filmDescribe;
	private String classifyText;
	private String img;
	private String url;
	private Date startTime;
	private Date createTime;
	private Date updateTime;

	public TFilm() {
	}

	public TFilm(String id) {
		this.id = id;
	}

	public TFilm(String id, String name, String describe, String classifyId, String classifyText, String img,
			String url, Date startTime, Date createTime, Date updateTime) {
		this.id = id;
		this.name = name;
		this.filmDescribe = filmDescribe;
		this.classifyText = classifyText;
		this.img = img;
		this.url = url;
		this.startTime = startTime;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public String getFilmDescribe() {
		return filmDescribe;
	}

	public void setFilmDescribe(String filmDescribe) {
		this.filmDescribe = filmDescribe;
	}

	public String getClassifyText() {
		return this.classifyText;
	}

	public void setClassifyText(String classifyText) {
		this.classifyText = classifyText;
	}

	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
