package com.lei.entity;
// Generated 2017-9-19 8:53:44 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TMenu generated by hbm2java
 */
public class TMenu implements java.io.Serializable {

	private String id;
	private TMenu TMenu;
	private String text;
	private String iconClas;
	private String url;
	private Set<TMenu> TMenus = new HashSet<TMenu>(0);

	public TMenu() {
	}

	public TMenu(String id) {
		this.id = id;
	}

	public TMenu(String id, TMenu TMenu, String text, String iconClas, String url, Set<TMenu> TMenus) {
		this.id = id;
		this.TMenu = TMenu;
		this.text = text;
		this.iconClas = iconClas;
		this.url = url;
		this.TMenus = TMenus;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TMenu getTMenu() {
		return this.TMenu;
	}

	public void setTMenu(TMenu TMenu) {
		this.TMenu = TMenu;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getIconClas() {
		return this.iconClas;
	}

	public void setIconClas(String iconClas) {
		this.iconClas = iconClas;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Set<TMenu> getTMenus() {
		return this.TMenus;
	}

	public void setTMenus(Set<TMenu> TMenus) {
		this.TMenus = TMenus;
	}

}
