package com.lei.entity;
// Generated 2017-9-21 11:26:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TNew generated by hbm2java
 */
public class TNews implements java.io.Serializable {

	private String id;
	private String title;
	private String text;
	private String intro;
	private Date createTime;
	private Date updateTime;
	
	public TNews() {
	}
	public TNews(String id) {
		this.id = id;
	}
	public TNews(String id, String title, String text, String intro, Date createTime, Date updateTime) {
		this.id = id;
		this.title = title;
		this.text = text;
		this.intro = intro;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getIntro() {
		return this.intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
